### ISSUE TITLE
Error, when set check_updates : false

### ISSUE THREAD

**Issue by xingren23** [Nourepide/ComfyUI-Allor#12]
Traceback (most recent call last):
  File "E:\stable_diffusion\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\stable_diffusion\ComfyUI\custom_nodes\ComfyUI-Allor\__init__.py", line 6, in <module>
    loader.check_updates()
  File "E:\stable_diffusion\ComfyUI\custom_nodes\ComfyUI-Allor\Loader.py", line 104, in check_updates
    repo = Repo(self.__root_path, odbt=git.db.GitDB)
                                       ^^^
UnboundLocalError: cannot access local variable 'git' where it is not associated with a value

Cannot import E:\stable_diffusion\ComfyUI\custom_nodes\ComfyUI-Allor module for custom nodes: cannot access local variable 'git' where it is not associated with a value

**Comment by Nourepide** [comment]
Hi! Sorry for long answer, your MR solves this issue?
