### ISSUE TITLE
Cannot import F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Allor module for custom nodes: Cmd('git') failed due to: exit code(128)   cmdline: git fetch -v -- origin

### ISSUE THREAD

**Issue by xueqing0622** [Nourepide/ComfyUI-Allor#42]
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Allor\__init__.py", line 7, in <module>
    loader.check_updates()
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Allor\Loader.py", line 208, in check_updates
    repo.remotes.origin.fetch()
  File "F:\ComfyUI\python_embeded\Lib\site-packages\git\remote.py", line 1069, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python_embeded\Lib\site-packages\git\remote.py", line 895, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "F:\ComfyUI\python_embeded\Lib\site-packages\git\cmd.py", line 834, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v -- origin
  stderr: 'fatal: unable to access 'https://mirror.ghproxy.com/https://github.com/Nourepide/ComfyUI-Allor/': Recv failure: Connection was reset'

Cannot import F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Allor module for custom nodes: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v -- origin
  stderr: 'fatal: unable to access 'https://mirror.ghproxy.com/https://github.com/Nourepide/ComfyUI-Allor/': Recv failure: Connection was reset'

**Comment by goodluck821** [comment]
Me too!

**Comment by goodluck821** [comment]
open the config.js, change the "day" to "month" or "year".

**Comment by Martyprod** [comment]
Hi, i add the same issue as i'm mainly offline 99% of the time, 
here is how i fixed it : (the answer is late.. sorry) but it can help other users :

The error happens because the ComfyUI-Allor node tries to check for updates from GitHub every time ComfyUI starts, even if you are offline. This causes the import to fail when there is no internet connection.

To fix this:

1. Open the file
`ComfyUI/custom_nodes/ComfyUI-Allor/__init__.py`

2. Find this line
`loader.check_updates()`

3. Comment it out by adding a # at the beginning, like this:
`# loader.check_updates()
`
4. Save the file and restart ComfyUI.
Now the node will work even when you are offline.
You can still update it manually when you are online if needed.

**Comment by xueqing0622** [comment]
thx,it works
