### ISSUE TITLE
Multiple Errors while installation but also when using the AlphaChannelAddByMask node with image batch.

### ISSUE THREAD

**Issue by Bl4ckh34d** [Nourepide/ComfyUI-Allor#9]
I am getting the following error when installing your repo. Despite the error I can access the nodes but get another error when I try to feed more than one image into the AlphaChannelAddByMask node.

First Error @ installation:
#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

## Execute install/(de)activation script for 'D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor'
 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
 Requirement already satisfied: rembg in d:\sd\comfyui\python_embeded\lib\site-packages (2.0.51)
 Requirement already satisfied: numpy in d:\sd\comfyui\python_embeded\lib\site-packages (from rembg) (1.26.1)
 Requirement already satisfied: onnxruntime in d:\sd\comfyui\python_embeded\lib\site-packages (from rembg) (1.16.1)
 Requirement already satisfied: opencv-python-headless in d:\sd\comfyui\python_embeded\lib\site-packages (from rembg) (4.7.0.72)
 Requirement already satisfied: pillow in d:\sd\comfyui\python_embeded\lib\site-packages (from rembg) (10.1.0)
 Requirement already satisfied: pooch in d:\sd\comfyui\python_embeded\lib\site-packages (from rembg) (1.7.0)
 Requirement already satisfied: pymatting in d:\sd\comfyui\python_embeded\lib\site-packages (from rembg) (1.1.10)
 Requirement already satisfied: scikit-image in d:\sd\comfyui\python_embeded\lib\site-packages (from rembg) (0.20.0)
 Requirement already satisfied: scipy in d:\sd\comfyui\python_embeded\lib\site-packages (from rembg) (1.11.3)
 Requirement already satisfied: tqdm in d:\sd\comfyui\python_embeded\lib\site-packages (from rembg) (4.66.1)
 Requirement already satisfied: coloredlogs in d:\sd\comfyui\python_embeded\lib\site-packages (from onnxruntime->rembg) (15.0.1)
 Requirement already satisfied: flatbuffers in d:\sd\comfyui\python_embeded\lib\site-packages (from onnxruntime->rembg) (23.5.26)
 Requirement already satisfied: packaging in d:\sd\comfyui\python_embeded\lib\site-packages (from onnxruntime->rembg) (23.2)
 Requirement already satisfied: protobuf in d:\sd\comfyui\python_embeded\lib\site-packages (from onnxruntime->rembg) (3.20.3)
 Requirement already satisfied: sympy in d:\sd\comfyui\python_embeded\lib\site-packages (from onnxruntime->rembg) (1.12)
 Requirement already satisfied: platformdirs>=2.5.0 in d:\sd\comfyui\python_embeded\lib\site-packages (from pooch->rembg) (3.11.0)
 Requirement already satisfied: requests>=2.19.0 in d:\sd\comfyui\python_embeded\lib\site-packages (from pooch->rembg) (2.31.0)
 Requirement already satisfied: numba!=0.49.0 in d:\sd\comfyui\python_embeded\lib\site-packages (from pymatting->rembg) (0.58.1)
 Requirement already satisfied: networkx>=2.8 in d:\sd\comfyui\python_embeded\lib\site-packages (from scikit-image->rembg) (3.1)
 Requirement already satisfied: imageio>=2.4.1 in d:\sd\comfyui\python_embeded\lib\site-packages (from scikit-image->rembg) (2.31.5)
 Requirement already satisfied: tifffile>=2019.7.26 in d:\sd\comfyui\python_embeded\lib\site-packages (from scikit-image->rembg) (2023.9.26)
 Requirement already satisfied: PyWavelets>=1.1.1 in d:\sd\comfyui\python_embeded\lib\site-packages (from scikit-image->rembg) (1.4.1)
 Requirement already satisfied: lazy_loader>=0.1 in d:\sd\comfyui\python_embeded\lib\site-packages (from scikit-image->rembg) (0.3)
 Requirement already satisfied: colorama in d:\sd\comfyui\python_embeded\lib\site-packages (from tqdm->rembg) (0.4.6)
 Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in d:\sd\comfyui\python_embeded\lib\site-packages (from numba!=0.49.0->pymatting->rembg) (0.41.1)
 Requirement already satisfied: charset-normalizer<4,>=2 in d:\sd\comfyui\python_embeded\lib\site-packages (from requests>=2.19.0->pooch->rembg) (3.3.0)
 Requirement already satisfied: idna<4,>=2.5 in d:\sd\comfyui\python_embeded\lib\site-packages (from requests>=2.19.0->pooch->rembg) (3.4)
 Requirement already satisfied: urllib3<3,>=1.21.1 in d:\sd\comfyui\python_embeded\lib\site-packages (from requests>=2.19.0->pooch->rembg) (2.0.6)
 Requirement already satisfied: certifi>=2017.4.17 in d:\sd\comfyui\python_embeded\lib\site-packages (from requests>=2.19.0->pooch->rembg) (2023.7.22)
 Requirement already satisfied: humanfriendly>=9.1 in d:\sd\comfyui\python_embeded\lib\site-packages (from coloredlogs->onnxruntime->rembg) (10.0)
 Requirement already satisfied: mpmath>=0.19 in d:\sd\comfyui\python_embeded\lib\site-packages (from sympy->onnxruntime->rembg) (1.3.0)
 Requirement already satisfied: pyreadline3 in d:\sd\comfyui\python_embeded\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime->rembg) (3.4.1)

## Execute install/(de)activation script for 'D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor'
 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
 Requirement already satisfied: onnx in d:\sd\comfyui\python_embeded\lib\site-packages (1.14.0)
 Requirement already satisfied: numpy in d:\sd\comfyui\python_embeded\lib\site-packages (from onnx) (1.26.1)
 Requirement already satisfied: protobuf>=3.20.2 in d:\sd\comfyui\python_embeded\lib\site-packages (from onnx) (3.20.3)
 Requirement already satisfied: typing-extensions>=3.6.2.1 in d:\sd\comfyui\python_embeded\lib\site-packages (from onnx) (4.8.0)

## Execute install/(de)activation script for 'D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor'
[!] ERROR: Invalid requirement: '# If you want you can install onnxruntime with GPU support'
install/(de)activation script failed: D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor

## Execute install/(de)activation script for 'D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor'
[!] ERROR: Invalid requirement: '# onnxruntime[gpu]'
install/(de)activation script failed: D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor

## Execute install/(de)activation script for 'D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor'
[!] ERROR: Invalid requirement: '# For Nvidia (only for GPU onnxruntime)'
install/(de)activation script failed: D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor

## Execute install/(de)activation script for 'D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor'
[!] ERROR: Invalid requirement: '# tensorrt'
install/(de)activation script failed: D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor

## Execute install/(de)activation script for 'D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor'
[!] ERROR: Invalid requirement: '# cuda-python'
install/(de)activation script failed: D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor

[ComfyUI-Manager] Startup script completed.
#######################################################################

Second error when feeding more than one image into the AlphaChannelAddByMask node:
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\SD\comfyui\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\comfyui\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\comfyui\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor\modules\AlphaChanel.py", line 70, in node
    return (torch.stack([
                        ^
  File "D:\SD\comfyui\ComfyUI\custom_nodes\ComfyUI-Allor\modules\AlphaChanel.py", line 75, in <listcomp>
    mask[i]
    ~~~~^^^
IndexError: index 1 is out of bounds for dimension 0 with size 1

**Comment by Nourepide** [comment]
Thanks, the issue with batch image processing in node AlphaChannelAddByMask should now be fixed by 777d98f 

![image](https://github.com/Nourepide/ComfyUI-Allor/assets/22074527/8ba9b081-8e5d-4b13-bb76-8169094af580)

What about the other errors? Try using the ImageSegmentation node and see if it works at all. I think the problem is in rembg.
